[greeter]
background=/usr/share/backgrounds/archmage/archmage-light.png
hide-user-image=true
theme-name=Arc-Dark-solid
icon-theme-name=Arc
cursor-theme-name=Breeze_Blue
font-name=Open Sans 11
position=30%,end 50%,end
